### ISSUE TITLE
[BUG] - Overlay don't start

### ISSUE THREAD

**Issue by jesuislapurete** [DorielRivalet/mhfz-overlay#239]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Hello, Everytime i launch my overlay it has a fatal error: 
![Capture 1](https://github.com/DorielRivalet/mhfz-overlay/assets/155062867/31e7a3ba-871c-428b-a0c3-1e009b403b2e)
Here is my crash log:
2023-12-26 17:27:27.8893|INFO|MHFZ_Overlay.App|Started WPF application
2023-12-26 17:27:27.9154|DEBUG|MHFZ_Overlay.App|OS: Microsoft Windows NT 10.0.19045.0, is64BitOS: True, is64BitProcess: False, CLR version: 6.0.8
2023-12-26 17:27:27.9154|INFO|MHFZ_Overlay.App|Found program version v0.32.0
2023-12-26 17:27:27.9346|INFO|MHFZ_Overlay.App|Created overlay shortcut
2023-12-26 17:27:29.8701|INFO|MHFZ_Overlay.App|Started WPF application
2023-12-26 17:27:29.8883|DEBUG|MHFZ_Overlay.App|OS: Microsoft Windows NT 10.0.19045.0, is64BitOS: True, is64BitProcess: False, CLR version: 6.0.8
2023-12-26 17:27:29.8883|INFO|MHFZ_Overlay.App|Found program version v0.32.0
2023-12-26 17:27:29.9676|INFO|MHFZ_Overlay.App|Running overlay for first time
2023-12-26 17:27:30.9576|INFO|MHFZ_Overlay.App|Restore our settings backup if any. Destination: C:\Users\NAME\AppData\Local\Doriel_Rivalet\MHFZ_Overlay_Url_wlori2km5bew2irx33eydkwxy5zdggor\0.32.0.0\user.config. Source: C:\Users\NAME\AppData\Local\MHFZ_Overlay\app-0.32.0\..\last.config
2023-12-26 17:27:30.9576|INFO|MHFZ_Overlay.Services.FileService|File not found at C:\Users\NAME\AppData\Local\MHFZ_Overlay\app-0.32.0\..\last.config
2023-12-26 17:27:30.9576|INFO|MHFZ_Overlay.App|Reloaded default settings
2023-12-26 17:27:30.9576|INFO|MHFZ_Overlay.App|Rendering mode: Hardware
2023-12-26 17:27:30.9576|DEBUG|MHFZ_Overlay.App|App ctor Elapsed Time: 1217.7958 ms
2023-12-26 17:27:31.0270|DEBUG|MHFZ_Overlay.Services.DatabaseService|Singleton not found, creating instance.
2023-12-26 17:27:31.0270|INFO|MHFZ_Overlay.Services.DatabaseService|Service initialized
2023-12-26 17:27:31.0270|DEBUG|MHFZ_Overlay.Services.DatabaseService|Singleton found, returning instance.
2023-12-26 17:27:31.0270|INFO|MHFZ_Overlay.DataLoader|DataLoader initialized
2023-12-26 17:27:31.8765|INFO|MHFZ_Overlay.DataLoader|Loading MHFODLL
2023-12-26 17:27:32.6677|ERROR|MHFZ_Overlay.DataLoader|Could not create code cave|System.ComponentModel.Win32Exception (299): Seule une partie d’une requête ReadProcessMemory ou WriteProcessMemory a été effectuée.
   at System.Diagnostics.NtProcessManager.EnumProcessModulesUntilSuccess(SafeProcessHandle processHandle, IntPtr[] modules, Int32 size, Int32& needed)
   at System.Diagnostics.NtProcessManager.GetModules(Int32 processId, Boolean firstModuleOnly)
   at System.Diagnostics.Process.get_Modules()
   at MHFZ_Overlay.DataLoader.LoadMHFODLL(Int32 pID)
   at MHFZ_Overlay.DataLoader.CreateCodeCave(Int32 pID)
   at MHFZ_Overlay.DataLoader..ctor()
2023-12-26 17:27:34.6874|INFO|MHFZ_Overlay.DataLoader|Running game in Non-HGE
2023-12-26 17:27:34.6973|DEBUG|MHFZ_Overlay.Services.DatabaseService|Singleton found, returning instance.
2023-12-26 17:27:34.6973|INFO|MHFZ_Overlay.ViewModels.Windows.AddressModel|AddressModel initialized
2023-12-26 17:27:34.7095|FATAL|MHFZ_Overlay.DataLoader|Found duplicate game
2023-12-26 17:27:35.3413|DEBUG|MHFZ_Overlay.Services.DatabaseService|Singleton found, returning instance.
2023-12-26 17:27:35.3590|WARN|MHFZ_Overlay.Services.DatabaseService|Cannot store session time. dataSource: 
2023-12-26 17:27:35.3590|DEBUG|MHFZ_Overlay.Services.DatabaseService|Singleton found, returning instance.
2023-12-26 17:27:35.3628|DEBUG|MHFZ_Overlay.Services.DatabaseService|Singleton found, returning instance.
2023-12-26 17:27:35.3628|DEBUG|MHFZ_Overlay.Services.AudioService|Singleton not found, creating instance.
2023-12-26 17:27:35.3628|INFO|MHFZ_Overlay.Services.AudioService|Service initialized
2023-12-26 17:27:35.3628|DEBUG|MHFZ_Overlay.Services.AudioService|Singleton found, returning instance.
2023-12-26 17:27:35.3628|DEBUG|MHFZ_Overlay.Services.AchievementService|Singleton not found, creating instance.
2023-12-26 17:27:35.3628|INFO|MHFZ_Overlay.Services.AchievementService|Service initialized
2023-12-26 17:27:35.3628|DEBUG|MHFZ_Overlay.Services.AchievementService|Singleton found, returning instance.
2023-12-26 17:27:35.3628|DEBUG|MHFZ_Overlay.Services.OverlaySettingsService|Singleton not found, creating instance.
2023-12-26 17:27:35.3628|INFO|MHFZ_Overlay.Services.OverlaySettingsService|Service initialized
2023-12-26 17:27:35.3628|DEBUG|MHFZ_Overlay.Services.OverlaySettingsService|Singleton found, returning instance.
2023-12-26 17:27:35.3628|DEBUG|MHFZ_Overlay.Services.DiscordService|Singleton not found, creating instance.
2023-12-26 17:27:35.3628|INFO|MHFZ_Overlay.Services.DiscordService|Service initialized
2023-12-26 17:27:35.3628|DEBUG|MHFZ_Overlay.Services.DiscordService|Singleton found, returning instance.
2023-12-26 17:27:35.3628|INFO|MHFZ_Overlay.Services.ApplicationService|Closing overlay
2023-12-27 19:09:25.6186|INFO|MHFZ_Overlay.App|Started WPF application
2023-12-27 19:09:25.6369|DEBUG|MHFZ_Overlay.App|OS: Microsoft Windows NT 10.0.19045.0, is64BitOS: True, is64BitProcess: False, CLR version: 6.0.8
2023-12-27 19:09:25.6369|INFO|MHFZ_Overlay.App|Found program version v0.32.0
2023-12-27 19:09:25.8047|INFO|MHFZ_Overlay.App|Restore our settings backup if any. Destination: C:\Users\NAME\AppData\Local\Doriel_Rivalet\MHFZ_Overlay_Url_wlori2km5bew2irx33eydkwxy5zdggor\0.32.0.0\user.config. Source: C:\Users\NAME\AppData\Local\MHFZ_Overlay\app-0.32.0\..\last.config
2023-12-27 19:09:25.8047|INFO|MHFZ_Overlay.Services.FileService|File not found at C:\Users\NAME\AppData\Local\MHFZ_Overlay\app-0.32.0\..\last.config
2023-12-27 19:09:25.8047|INFO|MHFZ_Overlay.App|Reloaded default settings
2023-12-27 19:09:25.8047|INFO|MHFZ_Overlay.App|Rendering mode: Hardware
2023-12-27 19:09:25.8047|DEBUG|MHFZ_Overlay.App|App ctor Elapsed Time: 322.6143 ms
2023-12-27 19:09:26.2170|DEBUG|MHFZ_Overlay.Services.DatabaseService|Singleton not found, creating instance.
2023-12-27 19:09:26.2170|INFO|MHFZ_Overlay.Services.DatabaseService|Service initialized
2023-12-27 19:09:26.2170|DEBUG|MHFZ_Overlay.Services.DatabaseService|Singleton found, returning instance.
2023-12-27 19:09:26.2170|INFO|MHFZ_Overlay.DataLoader|DataLoader initialized
2023-12-27 19:09:27.0597|INFO|MHFZ_Overlay.DataLoader|Loading MHFODLL
2023-12-27 19:09:27.8435|ERROR|MHFZ_Overlay.DataLoader|Could not create code cave|System.ComponentModel.Win32Exception (299): Seule une partie d’une requête ReadProcessMemory ou WriteProcessMemory a été effectuée.
   at System.Diagnostics.NtProcessManager.EnumProcessModulesUntilSuccess(SafeProcessHandle processHandle, IntPtr[] modules, Int32 size, Int32& needed)
   at System.Diagnostics.NtProcessManager.GetModules(Int32 processId, Boolean firstModuleOnly)
   at System.Diagnostics.Process.get_Modules()
   at MHFZ_Overlay.DataLoader.LoadMHFODLL(Int32 pID)
   at MHFZ_Overlay.DataLoader.CreateCodeCave(Int32 pID)
   at MHFZ_Overlay.DataLoader..ctor()
2023-12-27 19:09:33.2426|INFO|MHFZ_Overlay.DataLoader|Running game in Non-HGE
2023-12-27 19:09:33.3464|DEBUG|MHFZ_Overlay.Services.DatabaseService|Singleton found, returning instance.
2023-12-27 19:09:33.3464|INFO|MHFZ_Overlay.ViewModels.Windows.AddressModel|AddressModel initialized
2023-12-27 19:09:33.3584|FATAL|MHFZ_Overlay.DataLoader|Found duplicate game
2023-12-27 19:09:34.2065|DEBUG|MHFZ_Overlay.Services.DatabaseService|Singleton found, returning instance.
2023-12-27 19:09:34.2349|WARN|MHFZ_Overlay.Services.DatabaseService|Cannot store session time. dataSource: 
2023-12-27 19:09:34.3368|DEBUG|MHFZ_Overlay.Services.DatabaseService|Singleton found, returning instance.
2023-12-27 19:09:34.3368|DEBUG|MHFZ_Overlay.Services.DatabaseService|Singleton found, returning instance.
2023-12-27 19:09:34.3368|DEBUG|MHFZ_Overlay.Services.AudioService|Singleton not found, creating instance.
2023-12-27 19:09:34.3368|INFO|MHFZ_Overlay.Services.AudioService|Service initialized
2023-12-27 19:09:34.3368|DEBUG|MHFZ_Overlay.Services.AudioService|Singleton found, returning instance.
2023-12-27 19:09:34.3368|DEBUG|MHFZ_Overlay.Services.AchievementService|Singleton not found, creating instance.
2023-12-27 19:09:34.3368|INFO|MHFZ_Overlay.Services.AchievementService|Service initialized
2023-12-27 19:09:34.3368|DEBUG|MHFZ_Overlay.Services.AchievementService|Singleton found, returning instance.
2023-12-27 19:09:34.3368|DEBUG|MHFZ_Overlay.Services.OverlaySettingsService|Singleton not found, creating instance.
2023-12-27 19:09:34.3368|INFO|MHFZ_Overlay.Services.OverlaySettingsService|Service initialized
2023-12-27 19:09:34.3368|DEBUG|MHFZ_Overlay.Services.OverlaySettingsService|Singleton found, returning instance.
2023-12-27 19:09:34.3368|DEBUG|MHFZ_Overlay.Services.DiscordService|Singleton not found, creating instance.
2023-12-27 19:09:34.3368|INFO|MHFZ_Overlay.Services.DiscordService|Service initialized
2023-12-27 19:09:34.3368|DEBUG|MHFZ_Overlay.Services.DiscordService|Singleton found, returning instance.
2023-12-27 19:09:34.3368|INFO|MHFZ_Overlay.Services.ApplicationService|Closing overlay
2023-12-28 10:16:34.3019|INFO|MHFZ_Overlay.App|Started WPF application
2023-12-28 10:16:34.3186|DEBUG|MHFZ_Overlay.App|OS: Microsoft Windows NT 10.0.19045.0, is64BitOS: True, is64BitProcess: False, CLR version: 6.0.8
2023-12-28 10:16:34.3221|INFO|MHFZ_Overlay.App|Found program version v0.32.0
2023-12-28 10:16:34.4735|INFO|MHFZ_Overlay.App|Restore our settings backup if any. Destination: C:\Users\NAME\AppData\Local\Doriel_Rivalet\MHFZ_Overlay_Url_wlori2km5bew2irx33eydkwxy5zdggor\0.32.0.0\user.config. Source: C:\Users\NAME\AppData\Local\MHFZ_Overlay\app-0.32.0\..\last.config
2023-12-28 10:16:34.4735|INFO|MHFZ_Overlay.Services.FileService|File not found at C:\Users\NAME\AppData\Local\MHFZ_Overlay\app-0.32.0\..\last.config
2023-12-28 10:16:34.4762|INFO|MHFZ_Overlay.App|Reloaded default settings
2023-12-28 10:16:34.4762|INFO|MHFZ_Overlay.App|Rendering mode: Hardware
2023-12-28 10:16:34.4762|DEBUG|MHFZ_Overlay.App|App ctor Elapsed Time: 302.2792 ms
2023-12-28 10:16:34.9395|DEBUG|MHFZ_Overlay.Services.DatabaseService|Singleton not found, creating instance.
2023-12-28 10:16:34.9395|INFO|MHFZ_Overlay.Services.DatabaseService|Service initialized
2023-12-28 10:16:34.9395|DEBUG|MHFZ_Overlay.Services.DatabaseService|Singleton found, returning instance.
2023-12-28 10:16:34.9395|INFO|MHFZ_Overlay.DataLoader|DataLoader initialized
2023-12-28 10:16:35.7662|INFO|MHFZ_Overlay.DataLoader|Loading MHFODLL
2023-12-28 10:16:36.5529|ERROR|MHFZ_Overlay.DataLoader|Could not create code cave|System.ComponentModel.Win32Exception (299): Seule une partie d’une requête ReadProcessMemory ou WriteProcessMemory a été effectuée.
   at System.Diagnostics.NtProcessManager.EnumProcessModulesUntilSuccess(SafeProcessHandle processHandle, IntPtr[] modules, Int32 size, Int32& needed)
   at System.Diagnostics.NtProcessManager.GetModules(Int32 processId, Boolean firstModuleOnly)
   at System.Diagnostics.Process.get_Modules()
   at MHFZ_Overlay.DataLoader.LoadMHFODLL(Int32 pID)
   at MHFZ_Overlay.DataLoader.CreateCodeCave(Int32 pID)
   at MHFZ_Overlay.DataLoader..ctor()
2023-12-28 10:16:38.0600|INFO|MHFZ_Overlay.DataLoader|Running game in Non-HGE
2023-12-28 10:16:38.1125|DEBUG|MHFZ_Overlay.Services.DatabaseService|Singleton found, returning instance.
2023-12-28 10:16:38.1125|INFO|MHFZ_Overlay.ViewModels.Windows.AddressModel|AddressModel initialized
2023-12-28 10:16:38.9279|FATAL|MHFZ_Overlay.Services.LoggingService|Program crashed|System.ComponentModel.Win32Exception (299): Seule une partie d’une requête ReadProcessMemory ou WriteProcessMemory a été effectuée.
   at System.Diagnostics.NtProcessManager.EnumProcessModulesUntilSuccess(SafeProcessHandle processHandle, IntPtr[] modules, Int32 size, Int32& needed)
   at System.Diagnostics.NtProcessManager.GetModules(Int32 processId, Boolean firstModuleOnly)
   at System.Diagnostics.NtProcessManager.GetFirstModule(Int32 processId)
   at System.Diagnostics.Process.get_MainModule()
   at MHFZ_Overlay.DataLoader.CheckForIllegalModifications()
2023-12-28 10:16:44.1462|INFO|MHFZ_Overlay.Services.LoggingService|Opened with Notepad the file C:\Users\NAME\AppData\Local\MHFZ_Overlay\app-0.32.0\logs\logs.log
2023-12-28 10:16:44.1462|DEBUG|MHFZ_Overlay.Services.DatabaseService|Singleton found, returning instance.
2023-12-28 10:16:44.1716|WARN|MHFZ_Overlay.Services.DatabaseService|Cannot store session time. dataSource: 

### How often does the bug occur?

Always

### What version of the program are you using?

Latest version

**Comment by DorielRivalet** [comment]
Are you running multiple versions of the game?
Does it work on High Grade edition?
